### ISSUE TITLE
Missing Pages

### ISSUE THREAD

**Issue by sjpeters79** [open-data/od#117]
Below are pages missing in the D8 OD site that are available in the current D7 site:
- [x] /en/open-government-licence-canada
- [x] Bad url found on http://localhost/consultation/activities-discussion-action-plan-20-discussions: http://localhost/devel/node/url]/consultations/consultation-summaries; probably bad token replacement

**Comment by sylus** [comment]
I fixed all of the missing pages issue was  a problem with WB module, as for the second one am looking at reproducing it right now ^_^

**Comment by sylus** [comment]
Ok that last link for some reason was a panels landing page, I recreated it just via embedded data in fr + en for at least the link to work.
